[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {workspace = true}
clap = {workspace = true}
chrono = {workspace = true}
env_logger = "0.11.4"
log = {workspace = true}